-- Supabase SQL Editor에서 실행하세요.

create table lotto_draws (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  batch_id uuid not null default gen_random_uuid(),
  game_index int not null,
  numbers int[] not null
);

-- RLS 활성화: 클라이언트(anon key)에서 직접 접근하므로 반드시 켜야 합니다.
alter table lotto_draws enable row level security;

-- 익명 사용자가 새 행을 "추가"만 할 수 있도록 허용 (읽기/수정/삭제는 불가)
create policy "allow anonymous insert"
  on lotto_draws
  for insert
  to anon
  with check (true);
